image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
pages:
  stage: deploy
  script:
    - npm test && npm run build
  artifacts:
    paths:
      - public
  only:
    - master
